from __future__ import annotations

import argparse

from fevdecode.cli import cmd_sample_compare


def main() -> int:
    parser = argparse.ArgumentParser(prog="run_sample_compare")
    parser.add_argument("--fsb", required=True, help="input .fsb file")
    parser.add_argument(
        "--event-bank-json",
        required=True,
        help="event_bank_files.json generated by event-bank-files",
    )
    parser.add_argument(
        "--output",
        required=False,
        help="output CSV path or directory (default: alongside event_bank_files.json)",
    )
    parser.add_argument(
        "--rate-tolerance",
        type=float,
        default=0.01,
        help="allowed ratio drift between wav_rate and fsb_frequency (default: 0.01)",
    )
    parser.add_argument(
        "--duration-tolerance",
        type=float,
        default=0.01,
        help="allowed ratio drift between wav_duration and expected duration (default: 0.01)",
    )
    args = parser.parse_args()
    return cmd_sample_compare(args)


if __name__ == "__main__":
    raise SystemExit(main())